[package]
name = "logcrab"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Daniel Freiermuth"]

[features]
default = []
profiling = ["ram-profiling", "cpu-profiling"]
ram-profiling = ["dhat"]
cpu-profiling = ["puffin", "puffin_egui"]

[dependencies]
eframe = "0.28"
egui = "0.28"
egui_extras = "0.28"
egui_dock = "0.13"
keybinds = "0.2"
chrono = { version = "0.4", features = ["serde"] }
fancy-regex = "0.13"
lazy_static = "1.4"
ahash = "0.8"
rfd = "0.14"
dirs = "5.0"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
dhat = { version = "0.3", optional = true }
puffin = { version = "0.19", optional = true }
puffin_egui = { version = "0.29", optional = true }
